### ISSUE TITLE
unable to work

### ISSUE THREAD

**Issue by ongsici** [Dorniwang/PD-FGC-inference#2]
i tried using it on other faces and the generation failed terribly. there were numerous artefacts on the faces and it looks like a ghost. may I check if there are any requirements images? e.g. eyes must be at a certain level

**Comment by Dorniwang** [comment]
> i tried using it on other faces and the generation failed terribly. there were numerous artefacts on the faces and it looks like a ghost. may I check if there are any requirements images? e.g. eyes must be at a certain level

If you use your own images or videos, you need to preform preprocess first, the way how to preprocess images is in our readme, you can take it as a reference
