### ISSUE TITLE
A typo in Readme.md

### ISSUE THREAD

**Issue by YifengMa9** [Dorniwang/PD-FGC-inference#3]
Thanks for your remarkable work!

I may find a typo in Readme.md:

We propose -->Pose-Controllable Audio-Visual System (PC-AVS)<-- , We present a novel one-shot ...

**Comment by Dorniwang** [comment]
> Thanks for your remarkable work!
> 
> I may find a typo in Readme.md:
> 
> We propose -->Pose-Controllable Audio-Visual System (PC-AVS)<-- , We present a novel one-shot ...

Hi Yifeng,
Thank you for pointing out the typo, there maybe some oversights when I wrote the readme file. Now the readme file has been updated.
